### PR TITLE
Dark mode

### PR DESCRIPTION
**Pull request by sainiteshb**
I have addded dark mode to the app . Its working succesfully

### CODE REVIEW

**Comment by sainiteshb** [comment]
Screenshot_1602079644
Screenshot_1602079641

**Comment by Ashwinbicholiya** [comment]
There is some Overloaded error in home page.

**Comment by sainiteshb** [comment]
i have not changed any code , the emulator I'm using is 6 inch , maybe because of the height its showing because of the responsive problems already exists. You can check the code I changed. It was the same.

**Comment by sainiteshb** [comment]
maybe UI problem

**Comment by sainiteshb** [comment]
Dude, can you please respond?

**Comment by Ashwinbicholiya** [comment]
Wait I'll merge this pull request.

**Comment by Ashwinbicholiya** [comment]
Its not looks good.

**Comment by sainiteshb** [comment]
I just wasted my time for this , thank you

**Comment by Ashwinbicholiya** [comment]
Thank you for your time but you can see that if i apply this dark mode then UI will not looks good.

**Comment by sainiteshb** [comment]
then why did you assign me 😀

**Comment by Ashwinbicholiya** [comment]
you can add total in payment history same as In cart.
Then I'll accept your PR.
Don't be disappointed

**Pull request closed without merging**
